import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  resourcesSidebar: [
    'resources/index',
    {
      type: 'category',
      label: '学习地图与路径',
      collapsed: false,
      items: [
        'resources/hello-agents/index',
        'resources/ai-agents-from-zero/index',
        'resources/easy-vibe/index',
        'resources/codex-guide/index',
      ],
    },
    {
      type: 'category',
      label: 'Harness / Coding Agent',
      collapsed: false,
      items: [
        'resources/learn-claude-code/index',
        'resources/claude-code-architecture/index',
      ],
    },
    {
      type: 'category',
      label: '架构与生产化',
      collapsed: false,
      items: [
        'resources/agentic-design-patterns/index',
        'resources/ai-agent-book/index',
      ],
    },
    {
      type: 'category',
      label: '源码与真实系统',
      collapsed: false,
      items: [
        'resources/openclaw-book/index',
      ],
    },
  ],
  notesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'notes',
    },
  ],
  applicationNotesSidebar: [
    'application-notes/index',
    'application-notes/what-i-want-to-write-here',
    {
      type: 'category',
      label: 'Dify 架构拆解（v1.15.0）',
      collapsed: false,
      items: [
        'application-notes/dify/index',
        'application-notes/dify/dify-01-overview',
        'application-notes/dify/dify-02-app-config-layer',
        'application-notes/dify/dify-03-agent-runtime',
        'application-notes/dify/dify-04-agent-reasoning',
        'application-notes/dify/dify-05-agent-context',
        'application-notes/dify/dify-06-async-tasks-and-events',
        'application-notes/dify/dify-07-tool-registration',
        'application-notes/dify/dify-08-model-providers-and-extensions',
        'application-notes/dify/dify-09-rag-indexing',
        'application-notes/dify/dify-10-rag-retrieval',
        'application-notes/dify/dify-11-workflow-engine',
        'application-notes/dify/dify-12-mcp-protocol',
        'application-notes/dify/dify-13-multi-tenancy-and-security',
        'application-notes/dify/dify-14-observability',
        'application-notes/dify/dify-15-trigger-system',
        'application-notes/dify/dify-16-practice-and-deployment',
      ],
    },
    {
      type: 'category',
      label: 'Claude Code CLI 架构拆解',
      collapsed: false,
      items: [
        'application-notes/claude-code-cli/index',
        'application-notes/claude-code-cli/cc-01-layer-overview',
        'application-notes/claude-code-cli/cc-02-entry-and-lifecycle',
        'application-notes/claude-code-cli/cc-03-agent-loop',
        'application-notes/claude-code-cli/cc-04-streaming-and-rendering',
        'application-notes/claude-code-cli/cc-05-tool-execution-pipeline',
        'application-notes/claude-code-cli/cc-06-permission-security',
        'application-notes/claude-code-cli/cc-07-context-assembly',
        'application-notes/claude-code-cli/cc-08-compaction-subsystem',
        'application-notes/claude-code-cli/cc-09-skill-system',
        'application-notes/claude-code-cli/cc-10-subagent-isolation',
        'application-notes/claude-code-cli/cc-11-plan-mode-deep-dive',
        'application-notes/claude-code-cli/cc-12-hook-interception',
        'application-notes/claude-code-cli/cc-13-human-in-the-loop',
        'application-notes/claude-code-cli/cc-14-scheduled-tasks',
        'application-notes/claude-code-cli/cc-15-mcp-integration',
        'application-notes/claude-code-cli/cc-16-worktree-isolation',
        'application-notes/claude-code-cli/cc-17-persistence-and-cache',
        'application-notes/claude-code-cli/cc-18-observability',
      ],
    },
  ],
  templatesSidebar: [
    'templates/index',
    'templates/how-to-add-resource',
    'templates/human-first-contribution',
    'templates/ai-assisted-contribution',
    {
      type: 'category',
      label: '模板',
      collapsed: false,
      items: [
        'templates/resource-note-template',
        'templates/note-template',
      ],
    },
  ],
};

export default sidebars;
