import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  resourcesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'resources',
    },
  ],
  notesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'notes',
    },
  ],
  applicationNotesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'application-notes',
    },
  ],
};

export default sidebars;
